import { z } from 'zod';

export const aiChatSchema = z.object({
  body: z.object({
    message: z.string().min(1, 'Message cannot be empty').max(2000, 'Message is too long'),
    context: z.object({
      carbonResult: z.any().optional(), // Can be validated further if needed, but it's generated by backend initially
    }).optional(),
  }),
});
